USE [master]
GO

/****** Object:  Database [EWallet]    Script Date: 1/3/2021 18:09:59 ******/
CREATE DATABASE [EWallet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EWallet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EWallet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EWallet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EWallet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EWallet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EWallet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EWallet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EWallet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EWallet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EWallet] SET ARITHABORT OFF 
GO

ALTER DATABASE [EWallet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EWallet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EWallet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EWallet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EWallet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EWallet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EWallet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EWallet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EWallet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EWallet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EWallet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EWallet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EWallet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EWallet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EWallet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EWallet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EWallet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EWallet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EWallet] SET  MULTI_USER 
GO

ALTER DATABASE [EWallet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EWallet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EWallet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EWallet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EWallet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EWallet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EWallet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EWallet] SET  READ_WRITE 
GO


